version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/ApplicationCore/ApplicationCore.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output src/ApplicationCore/ApplicationCore.csproj
      - dotnet publish -c release -o ./build_output src/BlazorShared/BlazorShared.csproj
artifacts:
  files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml
